name: Monthly YouTube Channel Harvest
on:
  workflow_dispatch:

jobs:
  harvest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Authenticate to GCP
        run: |
          cat << 'EOF' > sa.json
${{ secrets.GCP_SA_KEY }}
EOF
          gcloud auth activate-service-account --key-file=sa.json
          gcloud config set project ${{ secrets.GCP_PROJECT }}

      - name: Run harvest script
        run: |
          python cc_index_only.py \
            --snapshot CC-MAIN-2024-10 \
            --dataset ${{ secrets.BQ_DATASET }} \
            --table   ${{ secrets.BQ_TABLE }}
