name: Monthly YouTube Channel Harvest
on:
  schedule:
    - cron: '0 3 1 * *'
  workflow_dispatch:
jobs:
  harvest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Authenticate to GCP
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > sa.json
          gcloud auth activate-service-account --key-file=sa.json
          gcloud config set project ${{ secrets.GCP_PROJECT }}
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      - name: Run harvest script
        run: |
          python cc_index_only.py \
            --snapshot CC-MAIN-2024-10 \
            --dataset ${{ secrets.BQ_DATASET }} \
            --table   ${{ secrets.BQ_TABLE }}
      - name: Commit CSV (if generated)
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[automated] Monthly harvest"
          file_pattern: "*.csv"
