name: Monthly YouTube Channel Harvest

on:
  workflow_dispatch:

jobs:
  harvest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch Common Crawl snapshot list via Python
        run: |
          python - <<'PYCODE'
          import requests, json, time, sys
          for i in range(5):
              try:
                  resp = requests.get("https://index.commoncrawl.org/collinfo.json", timeout=30)
                  resp.raise_for_status()
                  with open("collinfo.json","w") as f:
                      json.dump(resp.json(), f)
                  sys.exit(0)
              except Exception as e:
                  print(f"❗ attempt {i+1} failed: {e}", file=sys.stderr)
                  time.sleep((i+1)*5)
          print("❌ All attempts to fetch collinfo.json failed", file=sys.stderr)
          sys.exit(1)
          PYCODE

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Run harvest script
        run: |
          python cc_index_only.py \
            --year          2024 \
            --dataset       ${{ secrets.BQ_DATASET }} \
            --table         ${{ secrets.BQ_TABLE }} \
            --project       ${{ secrets.GCP_PROJECT }} \
            --collinfo-path collinfo.json
