name: Monthly YouTube Channel Harvest

on:
  workflow_dispatch:

jobs:
  harvest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Provide static snapshot list
        run: echo "Using checked‑in collinfo.json"

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Run harvest script
        run: |
          python cc_index_only.py \
            --year            2024 \
            --start-snapshot  CC-MAIN-2024-18 \
            --dataset         ${{ secrets.BQ_DATASET }} \
            --table           ${{ secrets.BQ_TABLE }} \
            --project         ${{ secrets.GCP_PROJECT }} \
            --collinfo-path   collinfo.json
